### ISSUE TITLE
Auto line breaks for long questions

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/Recipe#9]
![image](https://github.com/user-attachments/assets/cb32849d-20e7-4ac6-8d21-3abcbf91d0b5)

**Comment by JamesBremner** [comment]
This uses a new WINDEX feature. For your build you will need to update your WINDEX clone

**Comment by JamesBremner** [comment]
@lucasgsantos This was assigned to you 5 days ago.  Why are you ignoring it?  Why are you ignoring the three other issues also assigned to you last week?

**Comment by lucasgsantos** [comment]
I can't compile the source code. Broken references to windex. Yes, I did download the latest version of Recipe and windex

g++  -std=c++17 -g -D_mingw_ -Dvase \
-c -o .vscode/obj/cRecipeGUI.o ./src/cRecipeGUI.cpp -I./src -I./src/ext -I./models -I./models/basic -I../windex/include -I../raven-set
In file included from ./src/cRecipeGUI.cpp:7:
../windex/include/cxy.h: In static member function 'static bool cxy::isIntersection(cxy&, const cxy&, const cxy&, const cxy&, const cxy&)':
../windex/include/cxy.h:171:13: error: 'fabs' was not declared in this scope; did you mean 'labs'?
  171 |         if (fabs(det) < 0.0001)
      |             ^~~~
      |             labs
../windex/include/cxy.h: In static member function 'static double cxy::angle(const cxy&, const cxy&, const cxy&, const cxy&)':
../windex/include/cxy.h:208:16: error: 'atan2' was not declared in this scope
  208 |         return atan2(det, dot);
      |                ^~~~~
mingw32-make: *** [.vscode/makefile:41: .vscode/obj/cRecipeGUI.o] Error 1

 *  The terminal process "C:\msys64\ucrt64\bin\mingw32-make.exe '-f', '.vscode/makefile', 'rebuild'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by JamesBremner** [comment]
Please remember to assign issues to me, when you want me to work on them.

**Comment by JamesBremner** [comment]
Fixed.  You will need to update windex.

**Comment by lucasgsantos** [comment]
Still getting errors with windex references.

*  Executing task: C:\msys64\ucrt64\bin\mingw32-make.exe -f .vscode/makefile rebuild 

del /q .vscode\\obj\\*.o
g++  -std=c++17 -g -D_mingw_ -Dvase \
-c -o .vscode/obj/cRecipeGUI.o ./src/cRecipeGUI.cpp -I./src -I./src/ext -I./models -I./models/basic -I../windex/include -I../raven-set  
g++  -std=c++17 -g -D_mingw_ -Dvase \
-c -o .vscode/obj/cVase.o ./src/cVase.cpp -I./src -I./src/ext -I./models -I./models/basic -I../windex/include -I../raven-set  
g++  -std=c++17 -g -D_mingw_ -Dvase \
-c -o .vscode/obj/flower.o ./src/flower.cpp -I./src -I./src/ext -I./models -I./models/basic -I../windex/include -I../raven-set  
In file included from ./src/flower.cpp:6:
../windex/include/cxy.h:96:30: error: 'vector' in namespace 'std' does not name a template type
   96 |     bool isInside(const std::vector<cxy> &polygon) const
      |                              ^~~~~~
../windex/include/cxy.h:5:1: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
    4 | #include <cmath>
  +++ |+#include <vector>
    5 | 
../windex/include/cxy.h:96:36: error: expected ',' or '...' before '<' token
   96 |     bool isInside(const std::vector<cxy> &polygon) const
      |                                    ^
../windex/include/cxy.h:110:48: error: 'vector' in namespace 'std' does not name a template type
  110 |     static cxy enclosingWidthHeight(const std::vector<cxy> &polygon)
      |                                                ^~~~~~
../windex/include/cxy.h:110:43: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
  110 |     static cxy enclosingWidthHeight(const std::vector<cxy> &polygon)
      |                                           ^~~
../windex/include/cxy.h:110:54: error: expected ',' or '...' before '<' token
  110 |     static cxy enclosingWidthHeight(const std::vector<cxy> &polygon)
      |                                                      ^
../windex/include/cxy.h: In member function 'bool cxy::isInside(int) const':
../windex/include/cxy.h:99:14: error: 'vector' is not a member of 'std'
   99 |         std::vector<cxy>::const_iterator j = polygon.end() - 1;
      |              ^~~~~~
../windex/include/cxy.h:99:14: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
../windex/include/cxy.h:99:24: error: expected primary-expression before '>' token
   99 |         std::vector<cxy>::const_iterator j = polygon.end() - 1;
      |                        ^
../windex/include/cxy.h:99:27: error: '::const_iterator' has not been declared
   99 |         std::vector<cxy>::const_iterator j = polygon.end() - 1;
      |                           ^~~~~~~~~~~~~~
../windex/include/cxy.h:100:19: error: 'vector' is not a member of 'std'
  100 |         for (std::vector<cxy>::const_iterator i = polygon.begin();
      |                   ^~~~~~
../windex/include/cxy.h:100:19: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
../windex/include/cxy.h:100:29: error: expected primary-expression before '>' token
  100 |         for (std::vector<cxy>::const_iterator i = polygon.begin();
      |                             ^
../windex/include/cxy.h:100:32: error: '::const_iterator' has not been declared
  100 |         for (std::vector<cxy>::const_iterator i = polygon.begin();
      |                                ^~~~~~~~~~~~~~
../windex/include/cxy.h:101:14: error: 'i' was not declared in this scope
  101 |              i != polygon.end(); j = i++)
      |              ^
../windex/include/cxy.h:101:19: error: 'polygon' was not declared in this scope
  101 |              i != polygon.end(); j = i++)
      |                   ^~~~~~~
../windex/include/cxy.h:101:34: error: 'j' was not declared in this scope
  101 |              i != polygon.end(); j = i++)
      |                                  ^
../windex/include/cxy.h: In static member function 'static cxy cxy::enclosingWidthHeight(int)':
../windex/include/cxy.h:113:29: error: 'polygon' was not declared in this scope
  113 |         for (const cxy &p : polygon)
      |                             ^~~~~~~
mingw32-make: *** [.vscode/makefile:40: .vscode/obj/flower.o] Error 1

 *  The terminal process "C:\msys64\ucrt64\bin\mingw32-make.exe '-f', '.vscode/makefile', 'rebuild'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by JamesBremner** [comment]
I cannot reproduce this problem

```
In file included from ./src/flower.cpp:6:
../windex/include/cxy.h:96:30: error: 'vector' in namespace 'std' does not name a template type
96 | bool isInside(const std::vector &polygon) const
| ^~~~~~
../windex/include/cxy.h:5:1: note: 'std::vector' is defined in header ''; did you forget to '#include '?
```

It seems like the standard includes are arranged differently on your machine.  I have forced the vector to be included in cxy.h.  https://github.com/JamesBremner/windex/commit/1492e0a7b232b4a88fccad5d451fbaf11d03dea0

Please try again with an updated windex clone.
